image: gradle:alpine

stages:
  - build
  - test
  - deploy

variables:
  GIT_SSL_NO_VERIFY: 1

before_script:
  - echo "Start CI/CD"
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME
  - chmod +x ./gradlew

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  tags:
    - estg
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week

test-unit:
  stage: test
  only:
    - dev
  tags:
    - estg
  script:
    - ./gradlew test
    - ./gradlew jacocoTestReport
  artifacts:
    paths:
      - build/test-results/test/TEST-*.xml
      - build/reports/jacoco*

deploy:
  stage: deploy
  needs: [ test-unit ]
  only:
    - master
  script:
    - echo "Deploying..."

after_script:
  - echo "End CI/CD"
