image: gradle:alpine

stages:
  - build
  - test
  - deploy

variables:
  GIT_SSL_NO_VERIFY: 1

before_script:
  - echo "Start CI/CD"
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME
  - chmod +x ./gradlew

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

assemble:
  stage: build
  except:
    - main
  script:
    - ./gradlew --build-cache assemble

build:
  stage: build
  only:
    - main
  script:
    - ./gradlew --build-cache build
  artifacts:
    paths:
      - build/artifacts
    expire_in: 1 week

test:
  stage: test
  script:
    - ./gradlew test

deploy:
  stage: deploy
  needs: [test]
  only:
    - main
  script:
    - echo "Deploying..."

after_script:
  - echo "End CI/CD"

build-job:
  only:
    - none

unit-test-job:
  only:
    - none

lint-test-job:
  only:
    - none

deploy-job:
  only:
    - none
